//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El comentario seleccionado ya había sido resuelto..
        /// </summary>
        internal static string AlreadyResolvedComment {
            get {
                return ResourceManager.GetString("AlreadyResolvedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento inválida recibida: &quot;{0}&quot;..
        /// </summary>
        internal static string BirthdateIsInvalid {
            get {
                return ResourceManager.GetString("BirthdateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar usuario: miembro no válido o equipo completo..
        /// </summary>
        internal static string CannotAddUser {
            get {
                return ResourceManager.GetString("CannotAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar usuario: miembro no válido o equipo con mínimo de miembros..
        /// </summary>
        internal static string CannotRemoveUser {
            get {
                return ResourceManager.GetString("CannotRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inválida para la resolución del comentario recibida: es anterior a su creación..
        /// </summary>
        internal static string CannotResolveCommentBeforeCreation {
            get {
                return ResourceManager.GetString("CannotResolveCommentBeforeCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El comentario recibido ya se encuentra registrado..
        /// </summary>
        internal static string CommentAlreadyAdded {
            get {
                return ResourceManager.GetString("CommentAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El texto introducido para el comentario no es válido, reintente..
        /// </summary>
        internal static string CommentTextIsInvalid {
            get {
                return ResourceManager.GetString("CommentTextIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El comentario recibido no se encuentra en este usuario..
        /// </summary>
        internal static string CommentWasNotAdded {
            get {
                return ResourceManager.GetString("CommentWasNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha recibido un usuario creador inválido para el equipo ingresado: &quot;{0}&quot; no es miembro de &quot;{1}&quot;..
        /// </summary>
        internal static string CreatorIsInvalid {
            get {
                return ResourceManager.GetString("CreatorIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido recibido: &quot;{0}&quot;..
        /// </summary>
        internal static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ingresar una descripción vacía..
        /// </summary>
        internal static string EmptyDescription {
            get {
                return ResourceManager.GetString("EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura inválida recibida: genera situación en los cuales elementos escapan al pizarrón..
        /// </summary>
        internal static string HeightIsInvalid {
            get {
                return ResourceManager.GetString("HeightIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar cargar la imagen, verifique que la ruta que ha introducido es válida y no se ha movido o renombrado a la misma..
        /// </summary>
        internal static string ImageLoadingError {
            get {
                return ResourceManager.GetString("ImageLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máxima cantidad de miembros inválida: {0} (contiene actualmente {1})..
        /// </summary>
        internal static string InvalidMaximumMembers {
            get {
                return ResourceManager.GetString("InvalidMaximumMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido inválido: &quot;{0}&quot;..
        /// </summary>
        internal static string LastNameIsInvalid {
            get {
                return ResourceManager.GetString("LastNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre inválido: &quot;{0}&quot;. Éste debe contener únicamente caracteres alfanuméricos, o espacios..
        /// </summary>
        internal static string NameIsInvalid {
            get {
                return ResourceManager.GetString("NameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento inválido (no contenido) para el pizarrón actual recibido..
        /// </summary>
        internal static string NonMemberElement {
            get {
                return ResourceManager.GetString("NonMemberElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizarrón no válido recibido: no se encuentra asociado al equipo en cuestión..
        /// </summary>
        internal static string NotAddedWhiteboardRecieved {
            get {
                return ResourceManager.GetString("NotAddedWhiteboardRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento recibido es inválido (nulo)..
        /// </summary>
        internal static string NullElement {
            get {
                return ResourceManager.GetString("NullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inválido (nulo) recibido..
        /// </summary>
        internal static string NullUser {
            get {
                return ResourceManager.GetString("NullUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pizarrón recibido es inválido (nulo)..
        /// </summary>
        internal static string NullWhiteboard {
            get {
                return ResourceManager.GetString("NullWhiteboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de origen inválido recibido..
        /// </summary>
        internal static string OriginPointIsInvalid {
            get {
                return ResourceManager.GetString("OriginPointIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña inválida: &quot;{0}&quot;. Ésta debe tener un largo de entre {1} y {2} caracteres, y contener exclusivamente letras o números..
        /// </summary>
        internal static string PasswordIsInvalid {
            get {
                return ResourceManager.GetString("PasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizarrón no válido recibido: no es posible crear dos pizarrones con el mismo nombre asociados a un único equipo..
        /// </summary>
        internal static string RepeatedWhiteboardName {
            get {
                return ResourceManager.GetString("RepeatedWhiteboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo inválido (nulo) recibido..
        /// </summary>
        internal static string TeamIsInvalid {
            get {
                return ResourceManager.GetString("TeamIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los equipos deben contener al menos un miembro..
        /// </summary>
        internal static string TeamsCannotBeEmpty {
            get {
                return ResourceManager.GetString("TeamsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El comentario actual no se ha resuelto aún..
        /// </summary>
        internal static string UnresolvedComment {
            get {
                return ResourceManager.GetString("UnresolvedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre inválido: &quot;{0}&quot;..
        /// </summary>
        internal static string UserNameIsInvalid {
            get {
                return ResourceManager.GetString("UserNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho inválido recibido: genera situación en los cuales elementos escapan al pizarrón..
        /// </summary>
        internal static string WidthIsInvalid {
            get {
                return ResourceManager.GetString("WidthIsInvalid", resourceCulture);
            }
        }
    }
}
