//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Persistence.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario poder modificar al pizarrón para poder crear un comentario en este elemento..
        /// </summary>
        internal static string CannotCreateComment {
            get {
                return ResourceManager.GetString("CannotCreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible instanciar un repositorio genérico..
        /// </summary>
        internal static string CannotInstantiateRepository {
            get {
                return ResourceManager.GetString("CannotInstantiateRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible eliminar a todos los administradores del sistema; quedaría inutilizable..
        /// </summary>
        internal static string CannotRemoveAllAdministrators {
            get {
                return ResourceManager.GetString("CannotRemoveAllAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible eliminar al usuario: es el creador de algún pizarrón..
        /// </summary>
        internal static string CannotRemoveWhiteboardCreator {
            get {
                return ResourceManager.GetString("CannotRemoveWhiteboardCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los elementos recibidos ya se encuentran conectados..
        /// </summary>
        internal static string ConnectionAlreadyExists {
            get {
                return ResourceManager.GetString("ConnectionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los elementos recibidos no se encuentran asociados..
        /// </summary>
        internal static string ConnectionDoesNotExist {
            get {
                return ResourceManager.GetString("ConnectionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento que se intenta registrar ya existe en el sistema..
        /// </summary>
        internal static string ElementAlreadyExists {
            get {
                return ResourceManager.GetString("ElementAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento inválido recibido: no se encuentra registrado en el sistema..
        /// </summary>
        internal static string ElementDoesNotExist {
            get {
                return ResourceManager.GetString("ElementDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos de inicio de sesión ingresados no están asociados a ningún usuario, reintente..
        /// </summary>
        internal static string EmailPasswordMismatch {
            get {
                return ResourceManager.GetString("EmailPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recibió un elemento inválido..
        /// </summary>
        internal static string InvalidElementRecieved {
            get {
                return ResourceManager.GetString("InvalidElementRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario actual no tiene los permisos de administración requeridos para completar esta acción..
        /// </summary>
        internal static string NoAdministrationPrivileges {
            get {
                return ResourceManager.GetString("NoAdministrationPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una sesión activa en el sistema..
        /// </summary>
        internal static string SessionAlreadyStarted {
            get {
                return ResourceManager.GetString("SessionAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación inválida: no se ha iniciado sesión en el sistema aún..
        /// </summary>
        internal static string SessionNotStarted {
            get {
                return ResourceManager.GetString("SessionNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible que existan en el sistema dos equipos distintos con el mismo nombre..
        /// </summary>
        internal static string TeamNameMustBeUnique {
            get {
                return ResourceManager.GetString("TeamNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible modificar a un pizarrón sin ser miembro del equipo asociado al mismo o un administrador..
        /// </summary>
        internal static string UserCannotModifyWhiteboard {
            get {
                return ResourceManager.GetString("UserCannotModifyWhiteboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario ser el creador del pizarrón o un administrador del sistema para eliminarlo..
        /// </summary>
        internal static string UserCannotRemoveWhiteboard {
            get {
                return ResourceManager.GetString("UserCannotRemoveWhiteboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible tener dos usuarios registrados con la misma dirección de correo electrónico..
        /// </summary>
        internal static string UserEmailMustBeUnique {
            get {
                return ResourceManager.GetString("UserEmailMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible eliminar al usuario: es el único miembro de un equipo..
        /// </summary>
        internal static string UserIsLoneMemberOfSomeTeam {
            get {
                return ResourceManager.GetString("UserIsLoneMemberOfSomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró registro para el usuario en el equipo recibido..
        /// </summary>
        internal static string UserIsNotMemberOfTeam {
            get {
                return ResourceManager.GetString("UserIsNotMemberOfTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no es válido: no se encuentra registrado en el sistema..
        /// </summary>
        internal static string UserIsNotRegistered {
            get {
                return ResourceManager.GetString("UserIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El equipo &quot;{0}&quot; ya posee un pizarrón con el nombre &quot;{1}&quot;..
        /// </summary>
        internal static string WhiteboardNameTeamMustBeUnique {
            get {
                return ResourceManager.GetString("WhiteboardNameTeamMustBeUnique", resourceCulture);
            }
        }
    }
}
